doc: create skframe.md file
useradgents/skot pull request #62
Opened 2023-11-07 16:46 UTC by sylvainp

2023-11-09 07:46 UTC, sgueniot-ua requested changes

2023-11-09 07:46 UTC, sgueniot-ua commented on docs/components/framework_components/skframe.md
> +```
Peut-être différencier ça de la SKBottomSheet du coup

2023-11-13 13:15 UTC, sylvainp commented on docs/components/framework_components/skframe.md
> +```
J'ai trouvé cette utilisation du SKFrame dans Casino, c'est pour ça que l'ai mis en guise d'exemple d'utilisation dans le SKFrame et pas dans le SKBottomSheet 🤷🏻‍♂️ 

Tu préfères qu'on l'enlève @sgueniot-ua  ?

2023-11-13 13:29 UTC, sgueniot-ua commented on docs/components/framework_components/skframe.md
> +```
non pas forcement, je pense que la différence, c'est que la ta bottomsheet s'affiche tout le temps non ? c'est comme ça que je l'utiliserai moi, alors que la skBottomSheet c'est finalement une bottomSheetDialogFragment, un truc qui s'affiche au dessus et qui se ferme

2023-11-13 14:30 UTC, merged